# Generated by Django 2.2.3 on 2019-07-30 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='release_date',
            field=models.DateField(default=datetime.date(2019, 7, 29), verbose_name='Release Date'),
        ),
    ]
