# Generated by Django 2.2.3 on 2019-07-30 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190729_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='cover',
            field=models.ImageField(blank=True, upload_to='Movie'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='release_date',
            field=models.DateField(default=datetime.date(2019, 7, 30), verbose_name='Release Date'),
        ),
    ]
