# Generated by Django 2.2.3 on 2019-07-30 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190730_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='release_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Release Date'),
        ),
    ]
