# Generated by Django 2.2.3 on 2019-07-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20190730_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='cover',
            field=models.ImageField(upload_to='Movie'),
        ),
    ]
