# Generated by Django 2.2.3 on 2019-07-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20190730_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Movie'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
