# Generated by Django 2.2.3 on 2019-07-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20190730_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='cover',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='Movie'),
        ),
    ]
