# Generated by Django 2.2.3 on 2019-07-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20190730_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='cover',
            field=models.ImageField(blank=True, upload_to='Movie'),
        ),
    ]
