# Generated by Django 2.2.3 on 2019-07-31 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20190731_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
