# Generated by Django 2.2.3 on 2019-07-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20190731_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='poster_path',
            field=models.CharField(default='', max_length=256, verbose_name='Poster Path'),
        ),
    ]
