# Generated by Django 2.2.3 on 2019-07-31 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_moviereview_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='poster_path',
        ),
    ]
