# Generated by Django 2.2.3 on 2019-08-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_remove_moviereview_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='poster_path',
            field=models.CharField(default='', max_length=256, verbose_name='Poster Path'),
        ),
    ]
