# Generated by Django 2.2.3 on 2019-08-01 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_moviereview_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='poster_path',
        ),
    ]
