# Generated by Django 2.2.3 on 2019-07-22 06:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(default=0, verbose_name='Access Count')),
                ('code', models.CharField(max_length=8, verbose_name='Code')),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Upload Time')),
                ('download_path', models.CharField(max_length=64, verbose_name='Download Path')),
                ('file_name', models.CharField(default='', max_length=64, verbose_name='Filename')),
                ('file_size', models.CharField(max_length=10, verbose_name='File Size_KB')),
                ('upload_ip', models.CharField(default='', max_length=64, verbose_name='IP Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Information',
                'db_table': 'VideoInfo',
            },
        ),
    ]
