# Generated by Django 2.2.3 on 2019-07-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20190724_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='download_path',
            field=models.CharField(max_length=256, verbose_name='Download Path'),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='file_name',
            field=models.CharField(default='', max_length=256, verbose_name='Filename'),
        ),
    ]
