# Generated by Django 2.2.3 on 2019-07-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20190724_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='aws_file_name',
            field=models.CharField(default='', max_length=256, verbose_name='AWSFilename'),
        ),
    ]
