# Generated by Django 2.2.3 on 2019-07-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20190729_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoinfo',
            name='movie_name',
        ),
        migrations.RemoveField(
            model_name='videoinfo',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='videoinfo',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='videoinfo',
            name='release_date',
        ),
    ]
