# Generated by Django 2.2.3 on 2019-07-29 21:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0006_auto_20190729_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(default='', max_length=256, verbose_name='Movie name')),
                ('release_date', models.DateField(default=datetime.date(2019, 7, 29), verbose_name='Release date')),
                ('overview', models.TextField(blank=True)),
                ('rating', models.CharField(default='0.0', max_length=8, verbose_name='Rating')),
                ('cover', models.ImageField(upload_to='MovieCover')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movie Information',
                'db_table': 'Movie info',
            },
        ),
    ]
