# Generated by Django 2.2.3 on 2019-07-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_movieinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
